/*
 * scheduler.c
 *
 *  Created on: 13 Jun 2026
 *      Author: Yusha
 *
 * Deterministic model-step time base. See scheduler.h for the contract and the
 * rate setting (SCHED_RATE_HZ).
 *
 * TIM6 itself is configured by CubeMX (MX_TIM6_Init) - clock, prescaler/period
 * and NVIC all live in the .ioc, the intended way. This module only:
 *   - starts the timer interrupt (Sched_Init),
 *   - counts ticks in the HAL update callback,
 *   - hands ticks to the superloop with run-latest semantics (Sched_StepDue).
 * You never edit this file to add a Simulink signal.
 */

#include "scheduler.h"
#include "main.h"        /* HAL TIM API + the CubeMX-generated htim6 handle */

extern TIM_HandleTypeDef htim6;   /* defined by CubeMX in main.c (MX_TIM6_Init) */

/* g_sched_ticks: written only in the timer callback (the canonical tick count).
 * s_serviced / g_sched_overruns: written only by the loop. Single-writer each,
 * 32-bit aligned -> reads/writes are atomic on the M7, no masking needed. */
volatile uint32_t g_sched_ticks    = 0;
static   uint32_t s_serviced       = 0;
uint32_t          g_sched_overruns = 0;

void Sched_Init(void)
{
    /* Drop any update flag left from MX_TIM6_Init so the first tick is a full
     * period away, then enable the periodic update interrupt. */
    __HAL_TIM_CLEAR_FLAG(&htim6, TIM_FLAG_UPDATE);
    HAL_TIM_Base_Start_IT(&htim6);
}

bool Sched_StepDue(void)
{
    uint32_t ticks = g_sched_ticks;          /* atomic snapshot of the counter */

    if (ticks == s_serviced)
    {
        return false;                        /* no new tick since last step */
    }

    g_sched_overruns += (ticks - s_serviced) - 1u;   /* ticks we skipped over */
    s_serviced        = ticks;               /* jump to latest, no catch-up burst */
    return true;
}

/* HAL update callback, reached via TIM6_DAC_IRQHandler -> HAL_TIM_IRQHandler
 * (both generated by CubeMX). It is shared by every timer, so guard on the
 * instance - today only TIM6 uses it. Kept tiny: just count the tick. */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
    if (htim->Instance == TIM6)
    {
        g_sched_ticks++;
    }
}
